#!/bin/bash

# Determine the user's home directory
USER_HOME=$(eval echo ~${SUDO_USER})

# Specify the path to the virtual environment relative to the user's home directory
VENV_PATH="$USER_HOME/code/github.com/nathanbraun/techtools-pomodoro-api/venv/bin/python"

# Specify the path to your Python script
SCRIPT_PATH="$USER_HOME/code/github.com/nathanbraun/techtools-pomodoro-api/pomo.py"

# Execute the script with the virtual environment's Python interpreter
$VENV_PATH $SCRIPT_PATH "$@"
